"""Language normalization for TTS engines."""

OMNIVOICE_LANGUAGE_ALIASES = {
    "vie": "Vietnamese",
    "vi": "Vietnamese",
    "vietnamese": "Vietnamese",
    "eng": "English",
    "en": "English",
    "english": "English",
    "cmn": "Chinese",
    "zh": "Chinese",
    "chinese": "Chinese",
    "jpn": "Japanese",
    "ja": "Japanese",
    "japanese": "Japanese",
    "kor": "Korean",
    "ko": "Korean",
    "korean": "Korean",
    "fra": "French",
    "fr": "French",
    "french": "French",
    "deu": "German",
    "de": "German",
    "german": "German",
    "cam": "Khmer",
    "cambodia": "Khmer",
    "cambodian": "Khmer",
    "khm": "Khmer",
    "km": "Khmer",
    "khmer": "Khmer",
    "indo": "Indonesian",
    "indonesia": "Indonesian",
    "indonesian": "Indonesian",
    "id": "Indonesian",
    "ind": "Indonesian",
    "thai": "Thai",
    "thailand": "Thai",
    "th": "Thai",
    "tha": "Thai",
    "malay": "Malay",
    "malaysia": "Malay",
    "malaysian": "Malay",
    "ms": "Malay",
    "msa": "Malay",
    "singapore": "English",
    "singaporean": "English",
    "sg": "English",
    "mexico": "Spanish",
    "mexican": "Spanish",
    "spanish": "Spanish",
    "es": "Spanish",
    "spa": "Spanish",
    "bangladesh": "Bengali",
    "bangladeshi": "Bengali",
    "bengali": "Bengali",
    "bn": "Bengali",
    "ben": "Bengali",
}


def normalize_omnivoice_language(language: str | None) -> str:
    """Return the language name expected by OmniVoice."""
    if not language:
        return "Vietnamese"
    return OMNIVOICE_LANGUAGE_ALIASES.get(language.strip().lower(), language.strip())
